In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../ML_Datasets/unclean_smartwatch_health_data.csv")

In [4]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [8]:
df.sample(5)

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
9495,3334.0,87.538647,100.000000,14733.919388,7.938827546215321,Sedentary,9
6569,4877.0,64.713839,100.000000,1036.384521,6.329946814419157,Active,4
4460,4451.0,84.426347,98.033486,12335.520160,7.966832779476812,Seddentary,6
8154,2367.0,91.712668,100.000000,309.957005,6.574032098959562,Highly Active,3
4455,1261.0,59.001427,98.389782,149.755834,8.199249598391972,Highly_Active,1

In [10]:
df.describe()

           User ID  Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count  9799.000000       9600.000000             9700.000000   9900.000000
mean   3007.480253         76.035462               97.841581   6985.685885
std    1150.581542         19.412483                1.732863   6885.809680
min    1001.000000         40.000000               90.791208      0.910138
25%    1997.500000         64.890152               96.662683   2021.039657
50%    2998.000000         75.220601               98.010642   4962.534599
75%    4004.000000         85.198249               99.376179   9724.902880
max    4999.000000        296.593970              100.000000  62486.690753

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   object
 5   Activity Level          9800 non-null   object
 6   Stress Level            9800 non-null   object
dtypes: float64(4), object(3)
memory usage: 547.0+ KB

In [14]:
#### Missing values
df.isnull().sum()

User ID                   201
Heart Rate (BPM)          400
Blood Oxygen Level (%)    300
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [15]:
## Duplicate check
df.duplicated().sum()

np.int64(0)

In [ ]:
### Remove duplicates
df.drop_duplicates()

### Data Assessment
- What all different results we came up for our data

In [19]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [18]:
df.dropna(subset=['Heart Rate (BPM)'],inplace=True)

In [20]:
df.columns

Index(['User ID', 'Heart Rate (BPM)', 'Blood Oxygen Level (%)', 'Step Count',
       'Sleep Duration (hours)', 'Activity Level', 'Stress Level'],
      dtype='object')

In [21]:
df = df[['Heart Rate (BPM)', 'Blood Oxygen Level (%)', 'Step Count',
       'Sleep Duration (hours)', 'Activity Level', 'Stress Level']]

In [22]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(289)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9506 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9506 non-null   float32
 1   Blood Oxygen Level (%)  9506 non-null   float32
 2   Step Count              9506 non-null   float32
 3   Sleep Duration (hours)  9362 non-null   object
 4   Activity Level          9316 non-null   object
 5   Stress Level            9313 non-null   object
dtypes: float32(3), object(3)
memory usage: 408.5+ KB

In [ ]:
df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean(),inplace=True)

In [35]:
df.dropna(subset=['Step Count'], inplace=True)

np.int64(0)

In [ ]:
df['Heart Rate (BPM)'] = df['Heart Rate (BPM)'].astype('float32')
df['Blood Oxygen Level (%)'] = df['Blood Oxygen Level (%)'].astype('float32')
df['Step Count'] = df['Step Count'].astype('float32')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9506 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9506 non-null   float32
 1   Blood Oxygen Level (%)  9506 non-null   float32
 2   Step Count              9506 non-null   float32
 3   Sleep Duration (hours)  9362 non-null   object
 4   Activity Level          9316 non-null   object
 5   Stress Level            9313 non-null   object
dtypes: float32(3), object(3)
memory usage: 408.5+ KB

In [37]:
df = df[df['Sleep Duration (hours)'] != 'ERROR']

In [39]:
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].astype('float32')

In [40]:
df['Sleep Duration (hours)'].max()

np.float32(12.140233)

In [52]:
df.dropna(subset=['Sleep Duration (hours)'], inplace=True)

In [41]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939777,98.809647,5450.390625,7.167236,Highly Active,1
3,40.000000,96.894211,13797.337891,7.367790,Actve,3
4,61.950165,98.583794,15679.067383,NaN,Highly_Active,6
5,96.285934,94.202911,10205.992188,8.378343,Highly_Active,10
6,47.272255,95.389763,3208.781250,7.871146,Seddentary,2

In [43]:
df['Activity Level'].isnull().sum()

np.int64(188)

In [44]:
df.dropna(subset=['Activity Level'], inplace=True)

In [47]:
df['Activity Level'].dtypes

dtype('O')

In [48]:
df['Stress Level'].isnull().sum()

np.int64(188)

In [49]:
df.dropna(subset=['Stress Level'], inplace=True)

In [50]:
df['Stress Level'].isnull().sum()

np.int64(0)

In [53]:
df.isnull().sum()

Heart Rate (BPM)          0
Blood Oxygen Level (%)    0
Step Count                0
Sleep Duration (hours)    0
Activity Level            0
Stress Level              0
dtype: int64