In [1]:
import  pandas as pd

In [3]:
bank = pd.read_csv("../ML_Datasets/Bank_Marketing_Original_Data.csv")

In [6]:
bank.sample(3)

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
23228,59,management,married,tertiary,no,0,no,no,cellular,27,aug,87,4,-1,0,unknown,no
22236,37,management,married,tertiary,no,292,no,no,cellular,21,aug,133,2,-1,0,unknown,no
2319,39,blue-collar,married,secondary,no,130,yes,no,unknown,13,may,141,6,-1,0,unknown,no

- Ordinal Column ---> Education
- Label Column ---> TARGET
- Nominal Column ---> Married, ....

In [5]:
bank['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [10]:
ordinal_data = bank[['Education']]

In [11]:
target_data = bank[['TARGET']]

In [13]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
le = LabelEncoder()
oe = OrdinalEncoder(categories=[['unknown', 'primary', 'secondary', 'tertiary']])

In [14]:
ordinal_data = oe.fit_transform(ordinal_data)

In [17]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

In [18]:
target_data = le.fit_transform(target_data)

C:\Users\vipin.kumar03\OneDrive - Motherson Group\Generative AI\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
target_data

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

#### One Hot Encoder
- Used when working with nominal data.

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder(sparse_output=False)

In [22]:
bank.sample()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
33393,28,technician,single,tertiary,no,387,yes,no,cellular,20,apr,205,1,82,1,failure,yes

In [24]:
nominal_data = bank[['Job','Marital','Default', 'Housing','Loan','contact','Month','poutcome']]

In [25]:
nominal_data

                Job   Marital Default Housing Loan    contact Month poutcome
0        management   married      no     yes   no    unknown   may  unknown
1        technician    single      no     yes   no    unknown   may  unknown
2      entrepreneur   married      no     yes  yes    unknown   may  unknown
3       blue-collar   married      no     yes   no    unknown   may  unknown
4           unknown    single      no      no   no    unknown   may  unknown
...             ...       ...     ...     ...  ...        ...   ...      ...
45206    technician   married      no      no   no   cellular   nov  unknown
45207       retired  divorced      no      no   no   cellular   nov  unknown
45208       retired   married      no      no   no   cellular   nov  success
45209   blue-collar   married      no      no   no  telephone   nov  unknown
45210  entrepreneur   married      no      no   no   cellular   nov    other

[45211 rows x 8 columns]

In [26]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [27]:
ohe.fit_transform(nominal_data)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(45211, 40))