## DataFrame
- A DataFrame in Python is a 2-dimensional, table-like data structure—think of it like an Excel sheet or a SQL table, but inside your code.
- A DataFrame has:
    - Rows → records (like entries)
    - Columns → fields (like name, age, etc.)
    - Index → row labels

- 🔹 Key Features
    - Structured like a table (rows & columns)
    - Can hold different data types in each column
    - Supports powerful operations like:
        - Filtering
        - Grouping
        - Aggregation
        - Joining (like SQL)


- 🔹 Real-Life Analogy
    - Excel sheet → DataFrame
    - Database table → DataFrame
    - CSV file → easily converted into DataFrame

- 🔹 Common Use Cases
    - Data analysis
    - Machine learning preprocessing
    - Reading files (CSV, Excel, JSON)
    - Reporting and dashboards

### 1. Create DataFrame from Dictionary

    - This method uses a dictionary where keys are column names and values are lists of data.

In [1]:
import pandas as pd

data = {
    'Name': ['Vipin', 'Rahul', 'Amit'],
    'Age': [25, 30, 28],
    'City': ['Delhi', 'Mumbai', 'Pune']
}

df = pd.DataFrame(data)
df

    Name  Age    City
0  Vipin   25   Delhi
1  Rahul   30  Mumbai
2   Amit   28    Pune

### 2. Create DataFrame from List of Dictionaries

    - Each dictionary represents a row in the DataFrame.

In [2]:
data = [
    {'Name': 'Vipin', 'Age': 25, 'City': 'Delhi'},
    {'Name': 'Rahul', 'Age': 30, 'City': 'Mumbai'},
    {'Name': 'Amit', 'Age': 28, 'City': 'Pune'}
]

df = pd.DataFrame(data)
df

    Name  Age    City
0  Vipin   25   Delhi
1  Rahul   30  Mumbai
2   Amit   28    Pune

### 3. Create DataFrame from List of Lists

    - Data is provided as rows (list of lists), and column names are specified separately.

In [3]:
data = [
    ['Vipin', 25, 'Delhi'],
    ['Rahul', 30, 'Mumbai'],
    ['Amit', 28, 'Pune']
]

columns = ['Name', 'Age', 'City']

df = pd.DataFrame(data, columns=columns)
df

    Name  Age    City
0  Vipin   25   Delhi
1  Rahul   30  Mumbai
2   Amit   28    Pune

### 4. Create DataFrame from CSV File

    This method reads data from a CSV (Comma Separated Values) file and converts it into a DataFrame.

    It is the most commonly used method in real-world data analysis.

In [9]:
df = pd.read_csv('student_depression_dataset.csv')
df.sample(10).head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27724,139723,Male,22,Visakhapatnam,Student,2,0,5.41,3,0,'5-6 hours',Moderate,M.Com,Yes,12,4,Yes,1
16412,83059,Male,28,Faridabad,Student,5,0,8.46,3,0,'7-8 hours',Unhealthy,BCA,No,11,4,No,1
9005,45383,Female,19,Ludhiana,Student,3,0,5.37,4,0,'More than 8 hours',Healthy,'Class 12',Yes,10,5,Yes,1
21926,110720,Male,23,Srinagar,Student,3,0,8.04,5,0,'5-6 hours',Moderate,B.Arch,No,9,3,Yes,0
27812,140173,Female,24,Kalyan,Student,4,0,5.87,2,0,'5-6 hours',Healthy,M.Com,No,0,4,No,0